# Generated by Django 2.2.4 on 2021-03-08 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0002_show_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='network',
            field=models.CharField(max_length=45),
        ),
        migrations.DeleteModel(
            name='Network',
        ),
    ]
